apps/home/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'

bucket_urls = [
    path("", views.BucketHome.as_view(), name="bucket"),
    path("download_obj/<str:key>", views.DownloadBucketObjectView.as_view(), name="download_obj_bucket"),
    path("delete_obj/<str:key>", views.DeleteBucketObjectView.as_view(), name="delete_obj_bucket"),
]

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("search_result/", views.SearchView.as_view(), name="search_result"),
    path("category/<slug:category>/", views.HomeView.as_view(), name="category_filter"),
    path("bucket/", include(bucket_urls)),
    path("<slug:slug>/", views.ProductDetailView.as_view(), name="product_detail"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path("create/", views.OrderCreateView.as_view(), name="order_create"),
    path("detail/<int:order_id>", views.OrderDetailView.as_view(), name="order_detail"),
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/add/<int:product_id>", views.CartAddView.as_view(), name="cart_add"),
    path("cart/remove/<int:product_id>", views.CartRemoveView.as_view(), name="cart_remove"),
    path("apply/<int:order_id>", views.CouponApplyView.as_view(), name="coupon_apply"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('apps.home.urls', namespace='home')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path("orders/", include('apps.orders.urls', namespace='orders')),
]

apps/home/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation

class Category(models.Model):
    parent = models.ForeignKey(
        "self", 
        verbose_name=_("Parent"), 
        on_delete=models.CASCADE, 
        blank=True, 
        null=True,
        related_name='sub_category'
    )
    name = models.CharField(_("name"), max_length=200)
    slug = models.SlugField(_("slug"), unique=True)

    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categories")

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("home:category_filter", kwargs={"category": self.slug})

class Product(models.Model):
    
    category = models.ManyToManyField(Category, verbose_name=_("category"), related_name='products')
    name = models.CharField(_("name"), max_length=200)
    description = models.TextField(_("description"))
    image = models.ImageField(_("image"))#, upload_to='products-%Y-%m-%d')
    available = models.BooleanField(_("is available"), default=True)
    slug = models.SlugField(_("slug"), unique=True)
    price = models.IntegerField(_("price"))
    created_at = models.DateField(_("created at"), auto_now=False, auto_now_add=True)
    updated_at = models.DateField(_("updated at"), auto_now=True, auto_now_add=False)
    comment = GenericRelation('Comment')

    
    class Meta:
        ordering = ('name',)
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("home:product_detail", kwargs={"slug": self.slug})


class Comment(models.Model):
    user = models.ForeignKey(get_user_model(), verbose_name=_("user"), on_delete=models.CASCADE)
    body = models.TextField(_("body"))
    
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")

    def __str__(self):
        return self.user.email

    def get_absolute_url(self):
        return reverse("Comment_detail", kwargs={"pk": self.pk})

apps/home/forms.py
from django import forms

class SearchForm(forms.Form):
    search = forms.CharField(max_length=200, required=False)

apps/home/views.py
from typing import Any
from django import http, views
from django.http.response import HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import render, redirect
from .models import Product, Category
from . import tasks
from django.contrib import messages
from utils import IsAdminUserMixin
from apps.orders.forms import CartAddForm
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import PermissionRequiredMixin
from .forms import SearchForm
from .documents import ProductDocument
from elasticsearch_dsl import MultiSearch
from django_elasticsearch_dsl.search import Search


class HomeView(views.View):
    template_name = "home/home.html"
    form_class = SearchForm

    def get(self, request, category=None):
        products = Product.objects.filter(available=True)
        categories = Category.objects.filter(parent=None)
        if category:
            products = products.filter(category__slug= category)
        return render(request, self.template_name, {'products': products, 'categories': categories})
    

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            search_results = ProductDocument.search().query(
                "multi_match", 
                query=cd['search'], 
                fields=['name', 'description', 'category.name']
            )
            response = search_results.execute()
            product_ids = [hit.meta.id for hit in response.hits]
            products = Product.objects.filter(available=True, id__in=product_ids)
            categories = Category.objects.filter(parent=None)
            return render(request, self.template_name, {'products': products, 'categories': categories})

class ProductDetailView(DetailView):
    model = Product
    template_name = "home/detail.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['form'] = CartAddForm()
        return context
    

class BucketHome(IsAdminUserMixin, views.View):
    template_name = "home/bucket.html"

    def get(self, request):
        objects = tasks.all_bucket_objects_task()
        return render(request, self.template_name, {'objects': objects})
    

class DeleteBucketObjectView(PermissionRequiredMixin, IsAdminUserMixin, views.View):
    permission_required = 'accounts.delete_user'

    # def dispatch(self, request, *args: Any, **kwargs: Any) -> HttpResponse:
    #     if not request.user.has_perm('accounts.delete_user'):
    #         raise PermissionDenied()
    #     return super().dispatch(request, *args, **kwargs)
    
    def get(self, request, key):
        tasks.delete_object_task.delay(key)
        messages.info(request, 'Object will delete soon...', 'info')
        return redirect('home:bucket')
    
class DownloadBucketObjectView(IsAdminUserMixin, views.View):
    def get(self, request, key):
        tasks.download_object_task.delay(key)
        messages.info(request, 'Object is downloading...', 'info')
        return redirect('home:bucket')
    

class SearchView(views.View):
    form_class = SearchForm
    template_name = 'home/search.html'

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            search_results = ProductDocument.search().query(
                "multi_match", 
                query=cd['search'], 
                fields=['name', 'description', 'category.name']
            )
            return render(request, self.template_name, {'search_results': search_results})

apps/home/templates/home/bucket.html
{% extends "base.html" %}

{% block content %}
<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Size</th>
        <th scope="col">Download</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
    {% for obj in objects %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ obj.key }}</td>
        <td>{{ obj.size|filesizeformat }}</td>
        <td><a href='{% url "home:download_obj_bucket" obj.key %}'>Download</a></td>
        <td><a href='{% url "home:delete_obj_bucket" obj.key %}'>Delete</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock content %}

apps/home/templates/home/detail.html
{% extends "base.html" %}
{% block content %}
    <img src="{{ product.image.url }}" class="figure-img img-fluid rounded" alt="..." width="300" height="300">
    <div class="card-body">
    <a class="card-title" href="{{ product.get_absolute_url }}">{{product.name}}</a>
    <p class="card-text">{{ product.description }}</p>
    <p class="card-text">{{ product.price }} Toman</p>
    <small class="card-text">{{ product.created_at }}</small>
    </div>
    <br/><br/>
    <form action="{% url "orders:cart_add" product.id %}" method='post'>
        {% csrf_token %}
        {{ form }}
        <input type='submit' value="Add to cart">
    </form>
{% endblock content %}

apps/home/templates/home/home.html
{% extends "base.html" %}
{% load static %}

{% block extera_headers %}
<link href="{% static "home/css/style.css" %}" rel="stylesheet">
{% endblock extera_headers %}

{% block content %}
    {% for category in categories %}
        <div class="btn-group">
            <a class="btn btn-info" href="{{ category.get_absolute_url }}">{{category.name}}</a>
            <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                {% for sub in category.sub_category.all %}
                <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
                {% endfor %}
                {% comment %} <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Separated link</a></li> {% endcomment %}
            </ul>
        </div>
    {% endfor %}
    </br></br>
    <h3>Hello</h3>    
    {% for product in products %}
        <div class="card" style="width: 17rem; display: inline-block;">
            <img src="{{ product.image.url }}" class="card-img-top" alt="..." width="17rem" height="220rem">
            <div class="card-body">
            <a class="card-title" href="{{ product.get_absolute_url }}">{{product.name}}</a>
            <p class="card-text">{{ product.price }} Toman</p>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

apps/home/templates/home/search.html
{% extends "base.html" %}

{% block content %}
    <table class="table table-dark table-striped">  
        {% for hit in search_results %}
            <tbody>
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url "home:product_detail" hit.slug %}">{{hit.name}}</a></td>
            </tr>
            </tbody>
        {% endfor %}
    </table>
{% endblock content %}