apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path("register/", views.UserRegisterView.as_view(), name="register"),
    path("verify/", views.UserRegisterVerifyCodeView.as_view(), name="verify_code"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("login-verify/", views.UserLoginVerifyCodeView.as_view(), name="login_verify_code"),
    path("logout/", views.UserLogoutView.as_view(), name="logout")
]

apps/home/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'

bucket_urls = [
    path("", views.BucketHome.as_view(), name="bucket"),
    path("download_obj/<str:key>", views.DownloadBucketObjectView.as_view(), name="download_obj_bucket"),
    path("delete_obj/<str:key>", views.DeleteBucketObjectView.as_view(), name="delete_obj_bucket"),
]

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("search_result/", views.SearchView.as_view(), name="search_result"),
    path("category/<slug:category>/", views.HomeView.as_view(), name="category_filter"),
    path("bucket/", include(bucket_urls)),
    path("<slug:slug>/", views.ProductDetailView.as_view(), name="product_detail"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path("create/", views.OrderCreateView.as_view(), name="order_create"),
    path("detail/<int:order_id>", views.OrderDetailView.as_view(), name="order_detail"),
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/add/<int:product_id>", views.CartAddView.as_view(), name="cart_add"),
    path("cart/remove/<int:product_id>", views.CartRemoveView.as_view(), name="cart_remove"),
    path("apply/<int:order_id>", views.CouponApplyView.as_view(), name="coupon_apply"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('apps.home.urls', namespace='home')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path("orders/", include('apps.orders.urls', namespace='orders')),
]

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }}">{{message}}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url "home:home" %}">Home</a>
            <a class="nav-link active" href="{% url "accounts:register" %}">Register</a>
            {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url "accounts:logout" %}">Logout</a>
            {% else %}
            <a class="nav-link active" href="{% url "accounts:login" %}">Login</a>
            {% endif %}
            {% if request.user.is_admin %}
            <a class="nav-link active" href="{% url "home:bucket" %}">bucket</a>
            {% endif %}
            <a class="nav-link active" href="{% url "orders:cart" %}">Cart({{ cart|length }})</a>
        </div>
        <form class="d-flex" role="search" action="{% url "home:home" %}" method='post'>
            {% csrf_token %}
            <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    
    </div>
</nav>